apiVersion: v1
data:
  COLLECTOR_ENDPOINT: http://phoenix:6006/v1/traces
  MAX_RETRIES: "3"
  MCP_JIRA_URL: http://mcp-atlassian:9000/sse
  REDIS_URL: redis://valkey:6379/0
immutable: false
kind: ConfigMap
metadata:
  name: x-beeai-agent-configmap
  namespace: jotnar-prod
