apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"valkey:prod"},"fieldPath":"spec.template.spec.containers[?(@.name==\"valkey\")].image"}]'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: valkey
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: valkey
        deployment: valkey
    spec:
      containers:
      - image: valkey:prod
        imagePullPolicy: IfNotPresent
        name: valkey
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: "200m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: valkey-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: valkey-data
        persistentVolumeClaim:
          claimName: valkey-data
