apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mcp-atlassian
spec:
  tags:
    - name: prod
      from:
        kind: DockerImage
        name: ghcr.io/sooperset/mcp-atlassian:latest
      importPolicy:
        # Periodically query registry to synchronize tag and image metadata.
        scheduled: true
  lookupPolicy:
    # allows all resources pointing to this image stream to use it in the image field
    local: true

