apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phoenix-data
  namespace: jotnar-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
