import logging
from pydantic import BaseModel, Field

from beeai_framework.context import RunContext
from beeai_framework.emitter import Emitter
from beeai_framework.tools import StringToolOutput, Tool, ToolRunOptions

from ..ewa_utils import get_tcms_run_details

logger = logging.getLogger(__name__)


class AnalyzeEwaTestRunToolInput(BaseModel):
    run_id: int = Field(description="TCMS Test Run ID (e.g., 12345)")


class AnalyzeEwaTestRunTool(Tool[AnalyzeEwaTestRunToolInput, ToolRunOptions, StringToolOutput]):
    name = "analyze_ewa_testrun"  # type: ignore
    description = (  # type: ignore
         "Analyzes a TCMS test run generated by Errata Workflow Automation (EWA) "
         "and creates a test-case by test-case report."
    )
    input_schema = AnalyzeEwaTestRunToolInput  # type: ignore

    def _create_emitter(self) -> Emitter:
        return Emitter.root().child(
            namespace=["tool", "analyze_ewa_testrun"],
            creator=self,
        )

    async def _run(
        self,
        input: AnalyzeEwaTestRunToolInput,
        options: ToolRunOptions | None,
        context: RunContext,
    ) -> StringToolOutput:
        try:
            # Fetch the TCMS run details
            run_details = get_tcms_run_details(input.run_id)

            # Return the formatted details
            return StringToolOutput(
                result=run_details
            )

        except Exception as e:
            logger.error(f"Failed to get TCMS run details for {input.run_id}: {e}")
            return StringToolOutput(
                result=f"Error: Failed to get TCMS run details for {input.run_id}: {str(e)}"
            )
