FROM fedora:42

RUN dnf install -y libxcb python3 python3-pip redis jq ansible-core

RUN curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | GOOSE_BIN_DIR=/usr/local/bin CONFIGURE=false bash

RUN useradd -m -G wheel goose && echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel-nopasswd

RUN mkdir -p /home/goose/.config/goose /home/goose/recipes /home/goose/playbooks /home/goose/roles
COPY ./goose-config.yaml /home/goose/.config/goose/config.yaml
RUN chown -R goose:goose /home/goose/.config /home/goose/playbooks /home/goose/roles

USER goose
WORKDIR /home/goose

ENTRYPOINT ["/usr/bin/bash"]
CMD ["-c", ". ~/.bashrc; /usr/local/bin/goose"]
