services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    command: ["--transport", "sse", "--port", "9000", "-vv"]
    restart: unless-stopped

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"  # UI and OTLP HTTP collector
      - "4317:4317"  # OTLP gRPC collector
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix-data:/mnt/data
    restart: unless-stopped

  adk-agent:
    depends_on:
      - mcp-atlassian
      - phoenix
    image: adk-agent
    build:
      context: .
      dockerfile: Containerfile
    env_file:
      - .env
    environment:
      - MCP_JIRA_URL=http://mcp-atlassian:9000/sse
      - COLLECTOR_ENDPOINT=http://phoenix:6006/v1/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://phoenix:4317
    volumes:
      - ./agents:/home/adk/agents:ro,z
      - ./wait_mcp_server.sh:/wait_mcp_server.sh:ro,z
    stdin_open: true
    tty: true
    restart: "no"

volumes:
  adk-data:
  phoenix-data:
