Host iad2
   Hostname bastion-iad2.corp.redhat.com
   GSSAPIAuthentication yes
   User redhat-ymir-agent
Host pkgs.devel.redhat.com
   ProxyJump iad2
   User redhat-ymir-agent
Host *
   ServerAliveInterval 60
   ServerAliveCountMax 15
