apiVersion: v1
data:
  QUERY: 'project = RHEL AND (labels = "ymir_todo" OR labels IN ("ymir_consolidate_base", "ymir_consolidate_next")) AND labels != "sustaining"'
immutable: false
kind: ConfigMap
metadata:
  name: jira-issue-fetcher-todo-env
