apiVersion: v1
data:
  IGNORED_COMPONENTS: "firefox,thunderbird,firefox-flatpak-container,thunderbird-flatpak-container,webkit2gtk3,openjdk,postfix,xorg-x11-server,xorg-x11-server-Xwayland"
  MAX_ISSUES: "20"
  LOGLEVEL: "INFO"
immutable: false
kind: ConfigMap
metadata:
  name: jira-issue-fetcher-env
