apiVersion: v1
data:
  QUERY: 'project = RHEL AND labels = "ymir_todo" AND fixVersion in ("rhel-9.8.z", "rhel-10.2.z", "rhel-9.8", "rhel-10.2", "rhel-9.9", "rhel-10.3", "rhel-8.10.z")'
immutable: false
kind: ConfigMap
metadata:
  name: jira-issue-fetcher-todo-env
