apiVersion: apps/v1
kind: Deployment
metadata:
  name: triage-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: triage-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: triage-agent
        deployment: triage-agent
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10-30-34-89.us-east-1.compute.internal
      containers:
      - args:
        - agents/triage_agent.py
        command:
        - /usr/bin/python
        env:
        - name: GITLAB_USER
          # Not envFrom to avoid importing GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitlab-env
              key: GITLAB_USER
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/certs/ca-bundle.crt
        envFrom:
        - configMapRef:
            name: agents-env
        - configMapRef:
            name: chat-env
        - configMapRef:
            name: endpoints-env

        image: 'beeai-agent:c10s'
        imagePullPolicy: Always
        name: triage-agent
        ports:
        - containerPort: 8080
          protocol: TCP
        # TODO: add limits on cpu and memory.
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /git-repos  # NOTE: This path must match GIT_REPO_BASEPATH in configmap/agents-env
          name: mcp-server-git-repos
        - mountPath: /home/beeai/rhel-config.json
          name: rhel-config
          subPath: rhel-config.json
        - mountPath: /etc/secrets/jotnar-vertex-prod.json
          name: vertex-key
          subPath: jotnar-vertex-prod.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      # TODO: this should be reset when we have enough data.
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mcp-server-git-repos
        persistentVolumeClaim:
          claimName: mcp-server-git-repos
      - name: rhel-config
        configMap:
          name: rhel-config
      - name: vertex-key
        secret:
          secretName: vertex-key
