apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mcp-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mcp-gateway
        deployment: mcp-gateway
    spec:
      containers:
      - args:
        - -m
        - ymir.tools.privileged.gateway
        command:
        - /usr/bin/python
        env:
        - name: GIT_REPO_BASEPATH
          valueFrom:
            configMapKeyRef:
              key: GIT_REPO_BASEPATH
              name: agents-env
        - name: SILENT_RUN
          value: "true"
        - name: SSE_PORT
          value: "8000"
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/certs/ca-bundle.crt
        envFrom:
        - secretRef:
            name: gitlab-env
        - configMapRef:
            name: jira-env
        - secretRef:
            name: jira-env
        - configMapRef:
            name: kerberos-env
        image: mcp-server:prod
        imagePullPolicy: Always
        name: mcp-gateway
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "200m"
            memory: 512Mi
          requests:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /git-repos  # NOTE: This path must match GIT_REPO_BASEPATH in configmap/agents-env
          name: mcp-server-git-repos
        - mountPath: /etc/secrets/redhat-ymir-agent.keytab
          name: redhat-ymir-agent-keytab
          subPath: redhat-ymir-agent.keytab
        - mountPath: /home/mcp/rhel-config.json
          name: rhel-config
          subPath: rhel-config.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mcp-server-git-repos
        persistentVolumeClaim:
          claimName: mcp-server-git-repos
      - name: redhat-ymir-agent-keytab
        secret:
          secretName: redhat-ymir-agent-keytab  # pragma: allowlist secret
      - name: rhel-config
        configMap:
          name: rhel-config
