apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "redis-commander:prod"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"redis-commander\")].image"
        }
      ]
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-commander
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-commander
        deployment: redis-commander
    spec:
      initContainers:
      - name: copy-config
        image: redis-commander:prod
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "cp -r /usr/local/lib/node_modules/redis-commander/config/. /config/"]
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - env:
        - name: REDIS_HOST
          value: valkey
        - name: REDIS_PORT
          value: "6379"
        image: redis-commander:prod
        imagePullPolicy: IfNotPresent
        name: redis-commander
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: "200m"
            memory: 128Mi
          requests:
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: config
          mountPath: /usr/local/lib/node_modules/redis-commander/config
      volumes:
      - name: config
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
