apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-atlassian
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mcp-atlassian
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mcp-atlassian
        deployment: mcp-atlassian
    spec:
      containers:
      - args:
        - --transport
        - sse
        - --port
        - "9000"
        - -vv
        env:
        - name: JIRA_PERSONAL_TOKEN
          valueFrom:
            secretKeyRef:
              key: JIRA_PERSONAL_TOKEN
              name: mcp-atlassian-secret
        - name: JIRA_URL
          valueFrom:
            secretKeyRef:
              key: JIRA_URL
              name: mcp-atlassian-secret
        image: mcp-atlassian:prod
        imagePullPolicy: Always
        name: mcp-atlassian
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: "200m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
