apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-server-git-repos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
