apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-server-git-repos
  annotations:
    trident.netapp.io/reclaimPolicy: Retain
    volume.beta.kubernetes.io/storage-provisioner: netapp.io/trident
  labels:
    paas.redhat.com/appcode: JTNR-001
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: netapp-nfs
  volumeMode: Filesystem
