apiVersion: v1
kind: Service
metadata:
  name: phoenix-db
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: phoenix-db
    deployment: phoenix-db
  sessionAffinity: None
  type: ClusterIP
