# https://github.com/sclorg/build-and-push-action
name: Build and push to quay.io registry
on:
  push:
    branches:
      - main
jobs:
  build-and-push-goose-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push goose to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: "jotnar"
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: "goose/container/Containerfile"
          docker_context: "."
          image_name: "goose"

  build-and-push-beeai-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: "Containerfile.c9s"
            tag: "c9s"
            description: "CentOS Stream 9"
          - dockerfile: "Containerfile.c10s"
            tag: "c10s"
            description: "CentOS Stream 10"
    steps:
      - name: Build and push beeai:${{ matrix.tag }} to quay.io registry (${{ matrix.description }})
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: "jotnar"
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: ${{ matrix.dockerfile }}
          docker_context: "."
          image_name: "beeai"
          tag: ${{ matrix.tag }}

  build-and-push-mcp-server:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push mcp-server to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: "jotnar"
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: "Containerfile.mcp"
          docker_context: "."
          image_name: "mcp-server"
          # tag: "staging"

  build-and-push-testing-farm-sse-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push testing-farm-sse-bridge to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: "jotnar"
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: "goose/testing-farm-sse-bridge/Containerfile"
          docker_context: "goose/testing-farm-sse-bridge/"
          image_name: "testing-farm-sse-bridge"

  build-and-push-jira-issue-fetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push jira-issue-fetcher to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: "jotnar"
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: "Containerfile.jira-issue-fetcher"
          docker_context: "."
          image_name: "jira-issue-fetcher"
          # tag: "staging"
