name: Check BeeAI agents in container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-in-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: check-agents-in-container
          - target: check-mcp-server-in-container
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
        podman --version
    - name: Build test image from Containerfile.tests
      run: |
        podman build --rm --tag beeai-tests -f Containerfile.tests ./beeai
    - name: Run ${{ matrix.target }} target
      env:
        CONTAINER_ENGINE: podman
        TEST_IMAGE: beeai-tests
      working-directory: beeai/
      run: make ${{ matrix.target }}
