name: Check BeeAI agents in container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-in-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: check-agents-in-container
          - target: check-mcp-server-in-container
          - target: check-jira-issue-fetcher-in-container
          - target: check-common-in-container
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
        podman --version
    - name: Build Fedora test image from Containerfile.tests
      run: |
        podman build --rm --tag beeai-tests -f Containerfile.tests .
    - name: Build CentOS Stream 9 test image from Containerfile.c9s-tests
      run: |
        podman build --rm --tag beeai-tests-c9s -f Containerfile.c9s-tests .
    - name: Run ${{ matrix.target }} target
      env:
        CONTAINER_ENGINE: podman
        TEST_IMAGE: beeai-tests
        TEST_IMAGE_C9S: beeai-tests-c9s
      run: make ${{ matrix.target }}
