import asyncio
import logging
import re

import nitrate
from beeai_framework.context import RunContext
from beeai_framework.emitter import Emitter
from beeai_framework.tools import StringToolOutput, Tool, ToolRunOptions
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# Include only meaningful lines from the notes
NOTES_INCLUDE_PATTERN = re.compile(r"CR#|=>|-files|-avc|beaker-task")
# Unless called with --full, skip the Errata Workflow caseruns
CASERUN_EXCLUDE_PATTERN = re.compile(r"Errata Workflow")


def get_tcms_run_details(run_id: str, *, full: bool = False, color: bool = False) -> str:
    """
    Fetches and filters TCMS test run details.
    """
    if not color:
        nitrate.set_color_mode(nitrate.COLOR_OFF)
    else:
        nitrate.set_color_mode(nitrate.COLOR_ON)

    testrun = nitrate.TestRun(int(run_id))
    output = []

    for caserun in testrun.caseruns:
        caserun_str = str(caserun)
        notes_str = str(caserun.notes)

        passed = caserun.status == nitrate.Status("PASSED")

        output_entry = []
        if full:
            output_entry.append(caserun_str)
            output_entry.extend(notes_str.splitlines())
        else:
            # filter out Errata Workflow and not useful lines from notes
            if CASERUN_EXCLUDE_PATTERN.search(caserun_str):
                continue
            output_entry.append(caserun_str)
            # add the details from notes only for tests that do not pass
            if not passed:
                output_entry.extend(
                    line for line in notes_str.splitlines() if NOTES_INCLUDE_PATTERN.search(line)
                )
        if output_entry:
            output.append(output_entry)

    # Flatten the list of lists into a single list of strings
    flattened_output = [item for sublist in output for item in sublist]
    # Join the strings into a single multiline string
    return "\n".join(flattened_output)


class AnalyzeEwaTestRunToolInput(BaseModel):
    run_id: int = Field(description="TCMS Test Run ID (e.g., 12345)")


class AnalyzeEwaTestRunTool(Tool[AnalyzeEwaTestRunToolInput, ToolRunOptions, StringToolOutput]):
    name = "analyze_ewa_testrun"
    description = (
        "Analyzes a TCMS test run generated by Errata Workflow Automation (EWA) "
        "and creates a test-case by test-case report."
    )
    input_schema = AnalyzeEwaTestRunToolInput

    def _create_emitter(self) -> Emitter:
        return Emitter.root().child(
            namespace=["tool", "analyze_ewa_testrun"],
            creator=self,
        )

    async def _run(
        self,
        input: AnalyzeEwaTestRunToolInput,
        options: ToolRunOptions | None,
        context: RunContext,
    ) -> StringToolOutput:
        try:
            # Fetch the TCMS run details
            run_details = await asyncio.to_thread(get_tcms_run_details, input.run_id)

            # Return the formatted details
            return StringToolOutput(result=run_details)

        except Exception as e:
            logger.error(f"Failed to get TCMS run details for {input.run_id}: {e}")
            return StringToolOutput(result=f"Error: Failed to get TCMS run details for {input.run_id}: {e!s}")
